baseURL: "https://mjcet.wiki"
title: MJCETed
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: College
                  url: college
                  weight: 5
    
    urdu:
        languageName: "اردو"
        weight: 2
        menu:
            main:
                - name: محفوظ شدہ دستاویزات
                  url: archives
                  weight: 5
                - name: کالج
                  url: college
                  weight: 5


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Something"
    author: mjcet-chad
    # author: ["Me", "You"] # multiple authors

    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: true
    images: ["papermod-cover.png"]

    profileMode:
        enabled: false
        title: 
        imageUrl: "##"
        imageTitle: my image
        buttons:
            - name: Archive
              url: archive
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Welcome to MJCET wiki"
        Content: >
            ## MJCET Wikia

            <br>

            The MJCET College Guide:
            A project to create awareness in juniors by sharing our experiences. 
            Students from all colleges are welcome, but content will be focused around MJCET 
            to keep the guide relevant and avoid making it extremely generalized.

            <br>
            <br>
        

            ![nutsdeez](https://imgs.xkcd.com/comics/listening.png)

            <br>

            ![deeznuts](https://media.discordapp.net/attachments/853137341493542913/955857086238044200/unknown.png)



    socialIcons:
        - name: github
          url: "https://github.com/AbdulMalikDev/MjcetWiki"

    editPost:
        URL: "https://github.com/AbdulMalikDev/MjcetWiki/content"
        Text: "Suggest Changes" # edit text
        appendFilePath: true # to append file path to Edit link

taxonomies:
    category: categories
    tag: tags
    series: series

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: true
        # noClasses: false
        style: monokai

outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary



